name: CI - Node.js
on:<br/>
push:<br/>
branches: [ main ]
pull_request:
branches: [ main ]
jobs:<br/>
build-test:<br/>
runs-on: ubuntu-latest
steps:<br/>
- name: Baixar código do repositório
uses: actions/checkout@v4
- name: Configurar Node.js
uses: actions/setup-node@v4
with:
node-version: 20
- name: Instalar dependências
run: npm install
- name: Rodar testes
run: npm test
- name: Build
run: npm run build
