name: CI - Node.js

on:<br/>
  push:<br/>
    branches: [ main ]<br/>
    pull_request:<br/>
      branches: [ main ]
      
jobs:<br/>
  build-test:<br/>
    runs-on: ubuntu-latest
    
steps:<br/>
  - name: Baixar código do repositório<br/>
    uses: actions/checkout@v4
    
  - name: Configurar Node.js<br/>
    uses: actions/setup-node@v4<br/>
    with:<br/>
      node-version: 20
      
  - name: Instalar dependências<br/>
    run: npm install
    
  - name: Rodar testes<br/>
    run: npm test
    
  - name: Build<br/>
    run: npm run build
